### ISSUE TITLE
Ability to style the empty rows that are inserted by "emptyRowsWhenPaging"

### ISSUE THREAD

**Issue by TJHdev** [mbrn/material-table#1195]
Current I can't find a way to style the empty rows that are inserted. Being able to adjust the height of empty rows would be very useful for consistency of the table size.

**Comment by masbaehr** [comment]
Here's a hacky way to do it:

```css
tbody tr.MuiTableRow-root:not([index]) {
  display: none !important;
}
```
